### ISSUE TITLE
ERROR: Perf version 5.15 not supported on Icelake?

### ISSUE THREAD

**Issue by naromero77** [aayasin/perf-tools#57]
Thank you for creating such a nice tool and developing the TMA methodology.

I am on an IceLake system with Ubuntu 22.04.

I have perftools installed, but I get an error message that this version of perf is not supported. I am on the master branch.

~/perf-tools$ ./do.py setup-perf
ERROR: Unsupported perf tool: perf version 5.15.131 !

**Comment by aayasin** [comment]
Thanks for the compliments. 

You have a few options:

* build the latest good perf tool using
./do.py build-perf
and then pass the new binary via --perf to your profile comment.

* Unblock the specified perf version if your profiling doesn't need a delayed start, by deleting it's line from settings/perf-bad.txt

See do.py -h for more options and details of above.

**Comment by naromero77** [comment]
Thank you for the prompt response. I neglected to mention the part that does not make sense to me.

The error message is about perf 5.15, but it is also not listed in broken version of perf: https://github.com/aayasin/perf-tools/blob/master/settings/perf-bad.txt

Is there possibly some bug in how version's of bug are being excluded or am I miss reading how perf-bad.txt is being used (e.g. range instead of explicit list)?

Thank you.

**Comment by aayasin** [comment]
You are right. There was a bug where the code checked for a substring of the perf tool version
Fixed by https://github.com/aayasin/perf-tools/commit/826b17930738f8888e7322f1737dda309edc0286
