### ISSUE TITLE
peak4/5wide use uninitialized register

### ISSUE THREAD

**Issue by andikleen** [aayasin/perf-tools#82]
$PY ./gen-kernel.py -i NOP 'test %rax,%rax' 'jle Lbl_end' -n 1 -a 6 > peak4wide.c
$PY ./gen-kernel.py -i NOP NOP 'test %rax,%rax' 'jle Lbl_end' -n 1 -a 6 > peak5wide.c

But you randomly depend on rax being non zero, which is not always guaranteed based on compiler and runtime environment. The test can be fixed by adding

 register uint64_t a asm("rax") = 1;

    register uint64_t n asm ("r10");
    register uint64_t i0 asm ("r9");
    asm ("      mov %1,%0"
                 : "=r" (n)
                 : "r" ((uint64_t)ITER));
    asm("       PAUSE");
        asm(".align 64");
    for (i0=0; i0<n; i0++) {
        asm("   NOP");
        asm("   NOP");
        **asm("   test %rax,%rax");**
        asm("   jle Lbl_end");

**Comment by aayasin** [comment]
Thanks Andi for reporting this.

@amiri-khalil please see how to support this in a clean way in gen-kernel.py.
Basically, anytime ASM reads a register, it can be initialized in the loop prolog/epilog. Andi hints on one way so the compiler cannot disturb it.

Please fix it in build.sh, build.py and the auto way to get peak6wide (it has no dedicated source file in repo).
